### Shibu Kumari<br>190570107146

# LAB 6

# 1-Write a NumPy program to convert a list of numeric value into a one-     dimensional NumPy array

Step 1 : import numpy library
Step 2 : create list 
Step 3 : use function to create NumPy Array and pass list as argument
Step 4 : print NumPy array

In [1]:
import numpy as np
l = [12.23, 13.32, 100, 36.32]
print("Original List:",l)
a = np.array(l)
print("One-dimensional NumPy array: ",a)


Original List: [12.23, 13.32, 100, 36.32]
One-dimensional NumPy array:  [ 12.23  13.32 100.    36.32]


# 2-Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10

Step 1 : import numpy Library
Step 2 : use arange() function and pass 2,11 for range and for 3 * 3 matrix passs 3,3 in reshape() function
Step 3 : print matrix

In [2]:
import numpy as np
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


# 3-Write a NumPy program to create a null vector of size 10 and update sixth value to 11

Step 1 : import numpy Library
Step 2 : create vector of 10 size using zeros() function
Step 3 : assign 11 to 6th position of vector 
Step 4 : print vector

In [3]:
import numpy as np
x = np.zeros(10)
print(x)
print("Update sixth value to 11")
x[6] = 11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


# 4-Write a NumPy program to create an array with values ranging from 12 to 38

Step 1 : import numpy Library
Step 2 : use arange() function and pass 12,38 for creating array in range from 12 to 38
Step 3 : print array

In [4]:
import numpy as np
x = np.arange(12, 38)
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


# 5-Write a NumPy program compare two given arrays

Step 1 : import numpy Library
Step 2 : create two array using array function
Step 3 : use greater() fucntion and pass a,b(arrays) to check a > b
Step 4 : use greater_equal() fucntion and pass a,b(arrays) to check a >= b
Step 5 : use less() fucntion and pass a,b(arrays) to check a < b
Step 6 : use less_equal() fucntion and pass a,b(arrays) to check a <= b

In [1]:
import numpy as np
a = np.array([1, 2])
b = np.array([4, 5])
print("Array a: ",a)
print("Array b: ",b)
print("a > b")
print(np.greater(a, b))
print("a >= b")
print(np.greater_equal(a, b))
print("a < b")
print(np.less(a, b))
print("a <= b")
print(np.less_equal(a, b))

Array a:  [1 2]
Array b:  [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


# 6-Write a NumPy program to sort an along the first, last axis of an array

Step 1 : import numpy Library
Step 2 : create two numpy array
Step 3 : for sorting along the first axis : 
            use sort function pass (array,axis=0) then print array
Step 4 : for sorting along the last axis : 
            use sort function pass (array,axis=1) then print array

In [2]:
import numpy as np
a = np.array([[4, 6],[2, 1]])
print("Original array: ")
print(a)
print("Sort along the first axis: ")
x = np.sort(a, axis=0)
print(x)
print("Sort along the last axis: ")
y = np.sort(x, axis=1)
print(y)

Original array: 
[[4 6]
 [2 1]]
Sort along the first axis: 
[[2 1]
 [4 6]]
Sort along the last axis: 
[[1 2]
 [4 6]]


# 7-Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array

Step 1 : import numpy Library
Step 2 : create array
Step 3 : for finding values that are bigger than 10 
            use arrayname[arrayname > 10] and print
Step 4 : for finding their indices 
            use nonzero(arrayname > 10) and print 

In [3]:
import numpy as np
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(x)
print("Values bigger than 10 =", x[x>10])
print("Their indices are ", np.nonzero(x > 10))

Original array: 
[[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


# 8-Write a NumPy program to change the dimension of an array

Step 1 : import numpy Library
Step 2 : create array of (6,0)
Step 3 : create array of (3,3)
Step 4 : add more 3 values in array that we created first 
Step 5 : give (3,3) to arrayname.shape  (arrayname.shape=(3,3))
Step 6 : print array

In [5]:
import numpy as np
x = np.array([1, 2, 3, 4, 5, 6])
print("6 rows and 0 columns")
print(x.shape)

y = np.array([[1, 2, 3],[4, 5, 6],[7,8,9]])
print("(3, 3) -> 3 rows and 3 columns ")
print(y)

x = np.array([1,2,3,4,5,6,7,8,9])
print("Change array shape to (3, 3) -> 3 rows and 3 columns ")
x.shape = (3, 3)
print(x)

6 rows and 0 columns
(6,)
(3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Change array shape to (3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
